import Head from 'next/head'
import { Box, Typography } from '@mui/material'
import Link from 'next/link'



export default function Home() {
  
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <Box mt={5} >
           <Typography variant='h3' textAlign={'center'}  >  Welcome to <Link href="https://nextjs.org">Next.js!</Link> </Typography>
        </Box>

    </div>
  )
}
